[package]
name = "leit_index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Index construction and segment access for Leit"
keywords.workspace = true
categories.workspace = true

[dependencies]
bytemuck.workspace = true
leit_collect.workspace = true
leit_core.workspace = true
leit_postings.workspace = true
leit_query.workspace = true
leit_score.workspace = true
leit_text.workspace = true
memmap2 = { optional = true, workspace = true }

[features]
default = ["std"]
std = [
    "leit_collect/std",
    "leit_core/std",
    "leit_postings/std",
    "leit_query/std",
    "leit_score/std",
    "leit_text/std",
]
mmap = ["std", "dep:memmap2"]

[dev-dependencies]
proptest = { workspace = true }

[lints]
workspace = true
